### PR TITLE
Fix documentation files path

### PR DESCRIPTION
**Pull request by gpetrou**

### CODE REVIEW

**Comment by slozier** [comment]
Do we need the leading slashes?

**Comment by gpetrou** [comment]
Locally, yes but it seems we still need full path the CI builds, so I changed the parameter.

**Comment by slozier** [comment]
Hmm, I tried over here with just `$(AssemblyName).xml` and it worked fine.

**Comment by gpetrou** [comment]
In my case it creates the xml inside the project folder.

**Comment by slozier** [comment]
Odd. I wonder what the difference is...

**Pull request merged**
