### PR TITLE
Target .NET Standard 1.3 on CustomTasks

### PR DESCRIPTION
**Pull request by jp2masa**
## Changes
- Added a csproj for CustomTasks, which builds a netstandard1.3 assembly.
- Updated Bootstrap.targets to call MSBuild instead of Csc.

### CODE REVIEW

**Comment by slide** [comment]
Is there a reason to use netstandard1.3 instead of netstandard2.0?

**Comment by jp2masa** [comment]
There are many reasons, but the main one is that MSBuild doesn't target .NET Core 2.0 yet (it will on 15.6 I think).

**Comment by slide** [comment]
Ah, ok, so this is specifically because it's a custom task for msbuild. Understoond

**Comment by jp2masa** [comment]
It's also a good practice to target the smallest .NET Standard version possible, so that it works on more platforms.

**Pull request merged**
